---
  - include: centos.yml
    when: ansible_os_family == "Redhat"

  - include: debian.yml
    when: ansible_os_family == "Debian"

  - name: Defining Zabbix Database password
    lineinfile: dest=/etc/zabbix/zabbix_server.conf regexp="^# DBPassword=" insertafter="^# DBPassword=" line="DBPassword={{zabbix_db_pass}}" backup=yes backrefs=yes

  - name: Defining Zabbix mysql hosts
    lineinfile: dest=/etc/zabbix/zabbix_server.conf regexp="^# DBHost=localhost" insertafter="^# DBHost=localhost" line="DBHost={{zabbix_db_srv}}" backup=yes backrefs=yes

  - name: Defining Zabbix mysql user
    lineinfile: dest=/etc/zabbix/zabbix_server.conf regexp="^DBUser=" insertafter="^DBUser=" line="DBUser={{zabbix_db_user}}" backup=yes backrefs=yes

  - name: Defining Zabbix External scripts
    lineinfile: dest=/etc/zabbix/zabbix_server.conf regexp="^#/usr/lib/zabbix/externalscripts" insertafter="^/usr/lib/zabbix/externalscripts" line="{{zabbix_externalscripts}}" backup=yes backrefs=yes

  - name: Add Ansible warning txt block
    lineinfile: dest=/etc/zabbix/zabbix_server.conf
                regexp='# This'
                insertbefore=BOF
                line='#!!!This is an Ansible managed file!!!!'
                backrefs=yes

#  - name: Create externalscripts directory for Debian
#    file: path=/etc/zabbix/zabbix_agentd.d owner=root group=root mode=0755 state=directory
#    when: ansible_os_family == "Debian"

  - name: Uploading custom scripts (see files in role)
    copy: src={{item}} dest={{zabbix_externalscripts}}/{{item}} owner=root group=root mode=0755
    with_items:
      - zext_ssl_cert.sh

  - name: Uploading .my.cnf file for mysql monitoring (see files in role)
    template: src=.my.cnf.j2 dest=/etc/zabbix/.my.cnf owner=root group=root mode=0600

  - name: Upload files to zabbix_agent of hypervisor (see files in role)
    copy: src={{item}} dest=/etc/zabbix/zabbix_agentd.d/{{item}} owner=root group=root mode=0644
    with_items:
    - userparameter_mysql.conf

  - include: centos-post-install.yml
    when: ansible_os_family == "Redhat"

  - include: debian-post-install.yml
    when: ansible_os_family == "Debian"

  - debug: msg="Remember for a new zabbix server to import a sql file. you can do this be defining an extra var at playbook execution --extra-vars='database_first_import=true'"
